### ISSUE TITLE
Phone List not displaying Service point w/o people

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#19]
I need to add the Accommodations Testing/Tutoring Center number to the phone list.  I added it as a department and a service point of the DCL, but it doesn't display on the phone list.  Can you please make it display asap?  Thanks, Jessica

**Comment by jetapia** [comment]
Will you take a look at this tomorrow, Tracy?

**Comment by jetapia** [comment]
Oops, closed this by accident.  Will you take a look at this tomorrow, Tracy?

**Comment by trmccormick** [comment]
> Oops, closed this by accident. Will you take a look at this tomorrow, Tracy?

Not sure why it isn't showing. But I don't have admin access to the app to really check into this further.
