### ISSUE TITLE
Job Title should not be required

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#4]
I was trying to update Linda Bane's profile, and when I tried to save it, it said I had to have a job title.  For some employees, their university classification is all they have-- no additional job title.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by ddavisgraphics** [comment]
I thought I already removed that, I'll look into it.

**Comment by ddavisgraphics** [comment]
Fixed.
