### ISSUE TITLE
413 message

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#5]
**Describe the bug**
I tried to upload a photo that was too large-- 6.8mb and received a 413 Request Entity Too Large message from nginx.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddavisgraphics** [comment]
This has been fixed by adding a size parameter to the carrierwave uploader and by adjusting nginx to allow larger file sizes.
