### ISSUE TITLE
Preferred names/ Middle names

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#6]
**Describe the bug**
Not sure if this is really a bug or not, but if a person uses their middle name as their preferred name, and there's a middle name included, their name appears twice-- see Clifford Eugene Kyle-- currently shows up as Eugene Eugene Kyle.  This same thing will come up for Sarah Beth Royall (Beth Beth Royall).  Maybe if there's a preferred name both the first and middle should be replaced.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddavisgraphics** [comment]
This has been modified and tested.  All tests passed RSPEC and was modified to remove the middle name from the display_name when a preferred name is being used.
