### ISSUE TITLE
No star/requirement for middle name.

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#7]
**Describe the bug**
Middle names shouldn't be required.  Not sure if it it actually is or not in the code, but in the interface, it has a red * like it is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddavisgraphics** [comment]
A class was listed on the form element labeling it required, but it really was not required.  This issue has been fixed.
