### ISSUE TITLE
New users disabled by default?

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/library_directory#8]
**Describe the bug**
It seems that when you add a new user they are disabled by default, but I think it would make more sense for it to work the other way.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddavisgraphics** [comment]
This was fixed by adding a || to the selected view.  This issue is now added for users.
